baseURL = ""
languageCode = "en-us"
title = "JavaScripter"
theme = "kube"
description = "JavaScripter is a compilation of notes, cheatsheets, and diagrams during my journey from novice to full stack developer by Russell Rosario."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Russell Rosario" # add your company name
  github = "rosariorussell" # add your github profile name
  twitter = "russellrosario" # add your twitter profile
  email = "rosariorussell@gmail.com"

[[menu.main]]
    name = "Cheatsheets"
    weight = -100
    url = "/cheatsheets/"
[[menu.main]]
    name = "Diagrams"
    weight = -100
    url = "/diagrams/"
[[menu.main]]
    name = "Resources"
    weight = -100
    url = "/resources/"
[[menu.main]]
    name = "Tools"
    weight = -100
    url = "/tools/"
