baseURL = ""
languageCode = "en-us"
title = "Full Stack JavaScript Cheatsheets"
theme = "kube"
description = "Full Stack JavaScript Cheatsheets is the go-to resource for junior JavaScript developers"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "rosariorussell" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Cheatsheets"
    weight = -100
    url = "/cheatsheets/"
[[menu.main]]
    name = "Diagrams"
    weight = -100
    url = "/diagrams/"
[[menu.main]]
    name = "Resources"
    weight = -100
    url = "/resources/"
[[menu.main]]
    name = "Tools"
    weight = -100
    url = "/tools/"
